language: generic
sudo: required

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode9.4

env:
  - BUILD_TARGET=3.7 MINICONDA_VERSION=latest

addons:
  apt:
    packages:
      - libglew-dev
      - libicu-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - zlib1g-dev

services:
  - xvfb

before_install:
  # export BRANCH environment variable to have unified names across different CI services
  - export BRANCH=$TRAVIS_BRANCH
  # Used to label the uploads
  - export CONDA_LABEL=$(if [ "TRAVIS_PULL_REQUEST_BRANCH" == "master" ]; then echo main; else echo nightly; fi)
  # Download and install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # setup conda to always accept commands
  - conda config --set always_yes yes --set changeps1 no
  # unlink homebrew's boost to interfere with conda boost
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost; fi
  # Install conda packages necessary in the host to build the recipe
  - source activate base
  # conda install git and conda-build to build the package
  - conda install python=$BUILD_TARGET conda-build git
  # Print the conda info to facilitate the debugging
  - conda info -a
  # add conda channels
  - conda config --append channels salilab && conda config --append channels conda-forge
  - conda config --prepend channels tpeulen/label/nightly && conda config --prepend channels tpeulen
  - conda update -q conda
  - conda create -q -n build-environment python=$BUILD_TARGET conda-build anaconda-client jinja2 git nose coverage numpy pyyaml pysftp
  - source activate build-environment
  - conda build conda-recipe --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

install:
  # There is a problem for python >= 3.7.3
  # https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042003.html
  - conda install chisurf python=3.7.3

script:
  # osx does not have xvfb server for unit tests of gui
  # therefore run unitests on linux and on osx the conda
  # installation and startup.
  - export CONDA_LABEL=$(if [ "TRAVIS_PULL_REQUEST_BRANCH" == "master" ]; then echo main; else echo nightly; fi)
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      # Disable Numba JIT for correct coverage analysis
      export NUMBA_DISABLE_JIT=1
      pip install codacy-coverage
      python setup.py build_ext --inplace --force
      xvfb-run --server-args="-screen 0 1280x1024x24 +extension GLX" -a nosetests --with-coverage test/test_*.py;
      coverage xml
      python-codacy-coverage -r coverage.xml
    else
      chisurf&
      sleep 120
      pgrep -f chisurf | awk '{print "kill -9 " $1}' | sh
    fi

after_success:
  - OS=$TRAVIS_OS_NAME-64
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
      mkdir $TRAVIS_BUILD_DIR/dist
      cd build_tools/osx
        ./build-osx-app.sh \
        -f=$TRAVIS_BUILD_DIR/environment.yml \
        -i=$TRAVIS_BUILD_DIR/chisurf/gui/resources/icons/cs_logo.png \
        -n=ChiSurf \
        -m=chisurf \
        -p=$TRAVIS_BUILD_DIR \
        -o=$TRAVIS_BUILD_DIR/dist/osx
      cd ..
      python upload_sftp \
        -f "$TRAVIS_BUILD_DIR/dist/*.dmg" \
        -r "./downloads/macos_nightly.dmg"
    fi
#    if [[ "$TRAVIS_BRANCH" == "master" ]];
#    then
#      anaconda upload bld-dir/**/chisurf*.tar.bz2
#    fi

notifications:
  email:
    recipients:
      - thomas.otavio.peulen@gmail.com
    on_success: change # default:
    on_failure: change # default: always
