language: python
sudo: required
os:
  - linux
  - osx
services:
  - xvfb
python:
  - "3.7"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yaml
  - source activate chisurf
  - python setup.py build_ext --inplace --force
install:
  - python setup.py install
script:
  - source activate chisurf
  - conda install nose coverage
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  #- xvfb-run --server-args="-screen 0 1280x1024x24" nosetests --with-coverage test_*.py
  - nosetests --with-coverage test_*.py
after_success:
  - source activate chisurf
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
#  - conda install conda-build anaconda-client git
#  - git clone https://github.com/Fluorescence-Tools/conda-recipes.git
#  -
