name: chisurf

channels:
  - defaults
  - tpeulen
  - salilab
  - conda-forge

dependencies:
  - python =3.7.3
  - numpy
  - pyyaml >=5.0.0
  - qtpy >=1.8.0
  - pyqt >=5.13.0|5.9.2.*|5.6.0.*
  - pyqtgraph >0.10.0|0.9.10
  - typing_extensions
  - matplotlib >=3.0.0
  - scikit-fluorescence >=0.0.1
  - deprecation
  - progressbar2
  - python-slugify
  - cython >=0.25.0
  - numexpr >=2.6.0
  - numba >=0.48.0
  - scipy >=1.4.0
  - emcee 2.2.*
  - mdtraj >=1.9.0
  - ipython <=7.12.0
  - qtconsole <=4.6.0
  - jupyter_client 5.3.4.*
  - qscintilla2 >=2.9.3
  - guiqwt >=3.0.0
  - pymol-open-source >=2.3.0
  - pyopengl
  - pyopencl
  - python-docx 0.8.10.*
  - htmd-pdb2pqr 0.0.2.*
  - opencv >=3.4.0
  - mrcfile >=1.1.2
  - chinet >=0.0.5
  - scikit-fluorescence
  - ndxplorer
  - clsmview
  - k2dist
  - tttrconvert