name: docs_env
channels:
  - tpeulen/label/nightly
  - tpeulen
  - salilab
  - defaults
  - conda-forge
dependencies:
  - pip:
    - alabaster==0.7.12
    - babel==2.8.0
    - chardet==3.0.4
    - commonmark==0.9.1
    - deprecation==2.0.7
    - docutils==0.16
    - idna==2.9
    - imagesize==1.2.0
    - jinja2==2.11.1
    - latexcodec==2.0.0
    - matplotlib==2.2.3
    - numpy==1.18.2
    - numpydoc==0.9.2
    - oset==0.1.3
    - pybtex==0.22.2
    - pybtex-docutils==0.2.2
    - pyopengl==3.1.5
    - python-slugify==4.0.0
    - recommonmark==0.6.0
    - requests==2.23.0
    - snowballstemmer==2.0.0
    - sphinx==1.8.5
    - sphinx-autodoc-typehints==1.10.3
    - sphinx-bootstrap-theme==0.7.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==1.0.0
    - sphinxcontrib-websupport==1.2.1
    - urllib3==1.25.8
